"""initial schema

Revision ID: a3508d2fd73d
Revises: 
Create Date: 2026-02-18 17:07:38.006816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3508d2fd73d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market', sa.String(length=5), nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('stock_name', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.String(length=2000), nullable=True),
    sa.Column('content', sa.String(length=5000), nullable=True),
    sa.Column('sentiment', sa.String(length=10), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('news_score', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('theme', sa.String(length=100), nullable=True),
    sa.Column('is_disclosure', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_index(op.f('ix_news_event_market'), 'news_event', ['market'], unique=False)
    op.create_index('ix_news_event_market_stock', 'news_event', ['market', 'stock_code'], unique=False)
    op.create_index('ix_news_event_published', 'news_event', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_event_stock_code'), 'news_event', ['stock_code'], unique=False)
    op.create_table('stock_price',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=5), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('change_pct', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_price_code_date', 'stock_price', ['stock_code', 'date'], unique=True)
    op.create_index(op.f('ix_stock_price_stock_code'), 'stock_price', ['stock_code'], unique=False)
    op.create_table('theme_strength',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('market', sa.String(length=5), nullable=False),
    sa.Column('theme', sa.String(length=100), nullable=False),
    sa.Column('strength_score', sa.Float(), nullable=False),
    sa.Column('news_count', sa.Integer(), nullable=False),
    sa.Column('sentiment_avg', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'market', 'theme', name='uq_theme_date_market')
    )
    op.create_index(op.f('ix_theme_strength_date'), 'theme_strength', ['date'], unique=False)
    op.create_index(op.f('ix_theme_strength_market'), 'theme_strength', ['market'], unique=False)
    op.create_index(op.f('ix_theme_strength_theme'), 'theme_strength', ['theme'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_theme_strength_theme'), table_name='theme_strength')
    op.drop_index(op.f('ix_theme_strength_market'), table_name='theme_strength')
    op.drop_index(op.f('ix_theme_strength_date'), table_name='theme_strength')
    op.drop_table('theme_strength')
    op.drop_index(op.f('ix_stock_price_stock_code'), table_name='stock_price')
    op.drop_index('ix_stock_price_code_date', table_name='stock_price')
    op.drop_table('stock_price')
    op.drop_index(op.f('ix_news_event_stock_code'), table_name='news_event')
    op.drop_index('ix_news_event_published', table_name='news_event')
    op.drop_index('ix_news_event_market_stock', table_name='news_event')
    op.drop_index(op.f('ix_news_event_market'), table_name='news_event')
    op.drop_table('news_event')
    # ### end Alembic commands ###
